name: macOS Remote Access

on:
  workflow_dispatch:

jobs:
  secure-remote:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Remote Management (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all \
            -clientopts -setvnclegacy -vnclegacy yes -restart -agent

      - name: Create User with Secure Password
        run: |
          PASSWORD="Yaso1212"
          USERNAME="macuser"
          
          if ! id "$USERNAME" &>/dev/null; then
            sudo sysadminctl -addUser "$USERNAME" -password "$PASSWORD" -admin
          else
            echo "$PASSWORD" | sudo dscl . -passwd "/Users/$USERNAME"
          fi
          
          echo "REMOTE_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REMOTE_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://pkgs.tailscale.com/stable/Tailscale-1.86.4-macos.pkg -o /tmp/tailscale.pkg
          sudo installer -pkg /tmp/tailscale.pkg -target /
          rm /tmp/tailscale.pkg

      - name: Start Tailscale Connection
        run: |
          # البحث عن مسار Tailscale
          TAILSCALE_CMD=$(find /Applications -name "Tailscale" -type f -perm +111 2>/dev/null | head -1)
          
          if [ -z "$TAILSCALE_CMD" ]; then
            echo "❌ لم يتم العثور على Tailscale"
            exit 1
          fi

          # تشغيل Tailscale
          sudo "$TAILSCALE_CMD" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-mac-runner-$GITHUB_RUN_ID
          
          # الانتظار للحصول على IP
          for i in {1..30}; do
            TS_IP=$("$TAILSCALE_CMD" ip -4 2>/dev/null)
            if [ -n "$TS_IP" ]; then
              echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
              echo "✅ تم الحصول على IP: $TS_IP"
              break
            fi
            echo "الانتظار للحصول على IP من Tailscale..."
            sleep 10
          done

      - name: Display Connection Info
        run: |
          echo "=== معلومات الاتصال ==="
          echo "العنوان: $TAILSCALE_IP"
          echo "المستخدم: $REMOTE_USERNAME"
          echo "كلمة المرور: $REMOTE_PASSWORD"
          echo "استخدم VNC للاتصال على المنفذ 5900"
