name: macOS Remote Access

on:
  workflow_dispatch:

jobs:
  secure-remote:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Remote Management (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all \
            -clientopts -setvnclegacy -vnclegacy yes -restart -agent

      - name: Create User
        run: |
          USERNAME="macuser"
          PASSWORD="Yaso1212"
          
          if ! id "$USERNAME" &>/dev/null; then
            sudo sysadminctl -addUser "$USERNAME" -password "$PASSWORD" -admin
          fi
          
          echo "REMOTE_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REMOTE_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          # ุชุซุจูุช Tailscale ุจุงุณุชุฎุฏุงู ุงูุทุฑููุฉ ุงููุจุงุดุฑุฉ (ุจุฏูู Homebrew)
          curl -fsSL https://pkgs.tailscale.com/stable/Tailscale.pkg -o /tmp/tailscale.pkg
          sudo installer -pkg /tmp/tailscale.pkg -target /
          rm /tmp/tailscale.pkg

      - name: Start Tailscale Service
        run: |
          # ุจุฏุก ุฎุฏูุฉ Tailscale ูุฏููุงู
          echo "ุจุฏุก ุฎุฏูุฉ Tailscale..."
          sudo launchctl load /Library/LaunchDaemons/com.tailscale.tailscaled.plist
          
          # ุงูุงูุชุธุงุฑ ูุจุฏุก ุงูุฎุฏูุฉ
          sleep 15
          
          # ุงูุชุญูู ูู ุฃู ุงูุฎุฏูุฉ ุชุนูู
          if pgrep -q "tailscaled"; then
            echo "โ ุฎุฏูุฉ Tailscale ุชุนูู"
          else
            echo "โ ุฎุฏูุฉ Tailscale ูุง ุชุนูู"
            # ูุญุงููุฉ ุจุฏุก ุงูุฎุฏูุฉ ุจุทุฑููุฉ ุจุฏููุฉ
            sudo /Applications/Tailscale.app/Contents/MacOS/Tailscaled &
            sleep 10
          fi

      - name: Configure Tailscale Connection
        run: |
          # ุงูุงุชุตุงู ุจุดุจูุฉ Tailscale
          echo "ุฌุงุฑู ุงูุงุชุตุงู ุจุดุจูุฉ Tailscale..."
          sudo /Applications/Tailscale.app/Contents/MacOS/Tailscale up \
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
            --hostname=gh-runner-${{ github.run_id }} \
            --reset
          
          # ุงูุงูุชุธุงุฑ ููุญุตูู ุนูู IP
          echo "ุฌุงุฑู ุงูุชุธุงุฑ ุชุนููู ุนููุงู IP..."
          for i in {1..15}; do
            TS_IP=$(/Applications/Tailscale.app/Contents/MacOS/Tailscale ip -4 2>/dev/null || echo "")
            if [ -n "$TS_IP" ]; then
              echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
              echo "โ ุชู ุงูุญุตูู ุนูู IP: $TS_IP"
              break
            fi
            echo "ุงูุงูุชุธุงุฑ ููุญุตูู ุนูู IP... ($i/15)"
            sleep 5
          done
          
          if [ -z "$TS_IP" ]; then
            echo "โ ูุดู ูู ุงูุญุตูู ุนูู IP"
            echo "ุญุงูุฉ Tailscale:"
            /Applications/Tailscale.app/Contents/MacOS/Tailscale status || true
            exit 1
          fi

      - name: Verify Connection
        run: |
          echo "โ ุงูุงุชุตุงู ุจุดุจูุฉ Tailscale ูุงุฌุญ"
          echo "ุนููุงู IP: $TAILSCALE_IP"
          echo "ููููู ุงูุขู ุงูุงุชุตุงู ุจุงุณุชุฎุฏุงู VNC ุนูู ุงููููุฐ 5900"

      - name: Show Connection Info
        run: |
          echo "=========================================="
          echo "         ูุนูููุงุช ุงูุงุชุตุงู ุงูููุงุฆูุฉ         "
          echo "=========================================="
          echo "๐ก ุนููุงู IP: $TAILSCALE_IP"
          echo "๐ค ุงุณู ุงููุณุชุฎุฏู: $REMOTE_USERNAME"
          echo "๐ ูููุฉ ุงููุฑูุฑ: $REMOTE_PASSWORD"
          echo "๐ช ุงููููุฐ: 5900 (VNC)"
          echo "๐ ุงูุจุฑูุชูููู: VNC"
          echo "=========================================="
