name: macOS Remote Access

on:
  workflow_dispatch:

jobs:
  secure-remote:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Remote Management (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all \
            -clientopts -setvnclegacy -vnclegacy yes -restart -agent

      - name: Create User
        run: |
          USERNAME="macuser"
          PASSWORD="Yaso1212"
          
          if ! id "$USERNAME" &>/dev/null; then
            sudo sysadminctl -addUser "$USERNAME" -password "$PASSWORD" -admin
          fi
          
          echo "REMOTE_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "REMOTE_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale (Corrected)
        run: |
          # التأكد من تثبيت Homebrew أولاً
          if ! command -v brew &>/dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
            source ~/.zshrc
          fi
          
          # تصحيح اسم الحزمة إلى Tailscale (وليس Taliscale)
          brew install tailscale

      - name: Start and Configure Tailscale
        run: |
          # بدء خدمة Tailscale
          brew services start tailscale
          
          # الانتظار لبدء الخدمة
          sleep 10
          
          # الاتصال بشبكة Tailscale
          tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${{ github.run_id }} --reset
          
          # الانتظار للحصول على IP
          for i in {1..12}; do
            TS_IP=$(tailscale ip -4 2>/dev/null || echo "")
            if [ -n "$TS_IP" ]; then
              echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
              echo "✅ تم الحصول على IP: $TS_IP"
              break
            fi
            echo "الانتظار للحصول على IP من Tailscale... ($i/12)"
            sleep 5
          done
          
          if [ -z "$TS_IP" ]; then
            echo "❌ فشل في الحصول على IP"
            echo "حالة Tailscale:"
            tailscale status
            exit 1
          fi

      - name: Show Connection Info
        run: |
          echo "=== معلومات الاتصال ==="
          echo "IP: $TAILSCALE_IP"
          echo "المستخدم: $REMOTE_USERNAME"
          echo "كلمة المرور: $REMOTE_PASSWORD"
          echo "استخدم VNC على المنفذ 5900"
